config/routes.rb
Rails.application.routes.draw do
  root :to => "web/boards#show"

  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < User
end

app/models/manager.rb
class Manager < User
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :author, presence: true

  state_machine initial: :new_task do
    state :new_task
    state :in_development
    state :in_qa
    state :in_code_review
    state :ready_for_release
    state :released
    state :archived

    event :to_development do
      transition new_task: :in_development
      transition in_qa: :in_development
      transition in_code_review: :in_development
    end

    event :to_qa do
      transition in_development: :in_qa
    end

    event :passed_qa do
      transition in_qa: :in_code_review
    end

    event :passed_code_review do
      transition in_qa: :ready_for_release
    end

    event :to_release do
      transition ready_for_release: :released
    end

    event :to_archive do
      transition new_task: :archived
      transition released: :archived
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :my_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: /@/ }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/auth_helper.rb
module AuthHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def signed_in?
    current_user.present?
  end

  def authenticate_user!
    redirect_to(new_session_path) unless signed_in?
  end

  def current_user
    return if session[:user_id].blank?

    @_current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthHelper
  helper_method :current_user
end

app/controllers/web/boards_controller.rb
class Web::BoardsController < Web::ApplicationController
  def show; end
end

app/controllers/web/developers_controller.rb
class Web::DevelopersController < Web::ApplicationController
  def new
    @developer = Developer.new
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      sign_in(@developer)
      redirect_to(:board)
    else
      render(:new)
    end
  end

  private

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    @session = SessionForm.new
  end

  def create
    @session = SessionForm.new(session_params)

    if @session.valid?
      sign_in(@session.user)
      redirect_to(:board)
    else
      render(:new)
    end
  end

  def destroy
    sign_out
    redirect_to(:new_session)
  end

  private

  def session_params
    params.require(:session_form).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Task Manager"
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    - if !Rails.env.development?
      = stylesheet_packs_with_chunks_tag "application", media: "all"


  body
    = javascript_packs_with_chunks_tag 'application'
    header.mdl-layout__header
      .mdl-layout__header-row
        .material-icons tab
        label.mdl-button.mdl-js-button.mdl-button--icon
          i.material-icons
        span.mdl-layout-title
          = "Task Manager"
        .mdl-layout-spacer
        nav.mdl-navigation
          = link_to "Board", board_path, class: 'mdl-navigation__link'
          - if current_user
            - if current_user.is_a? Admin
              = link_to "Admin page", admin_users_url, class: 'mdl-navigation__link'
            = link_to "Log out", session_path, method: "delete", confirm: "confirm?", class: 'mdl-navigation__link'
          - else
            = link_to "Sign in", new_session_path, class: 'mdl-navigation__link'
            = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'
    main#main.mdl-layout__content
      .page-content
        = yield
    footer#footer.mdl-mini-footer
      .mdl-mini-footer__left-section
        .mdl-logo
          | &copy; Dualboot Learn 2020

app/views/web/boards/show.html.slim
h1 Web::Boards#show
p Find me in app/views/web/boards/show.html.slim

app/views/web/developers/new.html.slim
h3 Sign up

= simple_form_for @developer do |f|
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
  p
    = f.button :submit, "Sign up"